#!/bin/sh
. ../scripts/global_vars
cd CompleteModifierTest
/bin/rm -rf "$TMPCLASSOUT" 2>&1 >/dev/null
java -Xmx1024m -jar ../../FujiCompiler/build/fuji.jar -fopStatistic -d "$TMPCLASSOUT" CompleteModifierTestComp.features
