#!/bin/sh
. ../scripts/global_vars
cd CompleteModifierTest
/bin/rm -rf "$TMPCLASSOUT" >/dev/null 2>&1
java -Xmx1024m -jar ../../FujiCompiler/build/fuji.jar -d "$TMPCLASSOUT" CompleteModifierTestComp.features
