#!/bin/sh
. ../scripts/global_vars
cd Package-protected
/bin/rm -rf "$TMPCLASSOUT" 2>&1 >/dev/null
java -Ddebug -jar ../../FujiCompiler/build/fuji.jar -fopStatistic -d "$TMPCLASSOUT" Package-protectedComp.features
