#!/bin/sh
. ../scripts/global_vars

cd AHEAD
/bin/rm -rf "$TMPCLASSOUT"
java -Xmx128m -jar ../../FujiCompiler/build/fuji.jar -cp ../lib/jakarta.jar:../lib/ant.jar -d "$TMPCLASSOUT" Jak2JavaComp.features
