#!/bin/sh
. ../scripts/global_vars

cd BerkeleyDB-fuji-compilable
/bin/rm -rf "$TMPCLASSOUT"
java -Xmx128m -jar ../../FujiCompiler/build/fuji.jar -d "$TMPCLASSOUT" -cp ../lib/cide.jar BerkeleyDBComp.features
