#!/bin/sh
. ../scripts/global_vars

cd GameOfLife
/bin/rm -rf "$TMPCLASSOUT"
java -Xmx128m -jar ../../FujiCompiler/build/fuji.jar -d "$TMPCLASSOUT" -cp ../lib/junit.jar GameOfLifeComp.features
cp -rf GuiBase/ressources "$TMPCLASSOUT"
