#!/bin/sh
CL=classes
SR=sources

cd GUIDSL
/bin/rm -rf "$CL" "$SR"
java -Xmx128m -jar ../../FujiCompiler/build/fuji.jar -classpath '../lib/jakarta.jar:../lib/jdom.jar:../lib/sat4j.jar' -d "$CL" -src "$SR" GUIDSLComp.features
/bin/rm -rf "$CL"
mkdir classes
javac -cp '../lib/jakarta.jar:../lib/jdom.jar:../lib/sat4j.jar' -d classes \
    `find "$SR" -name '*.java'`
