#!/bin/sh
. ../scripts/global_vars

cd MobileMedia8-fuji-compilable
rm -rf "$TMPCLASSOUT"
java -jar ../../FujiCompiler/build/fuji.jar -d "$TMPCLASSOUT" -cp \
  /home/kolesnik/work/projects/fuji/FujiProject/trunk/examples/lib/cide.jar:\
/home/kolesnik/work/projects/fuji/FujiProject/trunk/examples/lib/midpapi21.jar:\
/home/kolesnik/work/projects/fuji/FujiProject/trunk/examples/lib/cldcapi11.jar:\
/home/kolesnik/work/projects/fuji/FujiProject/trunk/examples/lib/wma20.jar:\
/home/kolesnik/work/projects/fuji/FujiProject/trunk/examples/lib/mmapi.jar \
  MobileMedia8-fuji-compilableComp.features
