#!/bin/sh
. ../scripts/global_vars
cd Notepad
/bin/rm -rf "$TMPCLASSOUT"
java -Xmx128m -jar ../../FujiCompiler/build/fuji.jar -d "$TMPCLASSOUT" NotepadComp.features \
	&& /bin/cp -rf notepad_resources/* "$TMPCLASSOUT"
