#!/bin/sh
. ../scripts/global_vars
cd PKJab
/bin/rm -rf "$TMPCLASSOUT"
java -Xmx128m -jar ../../FujiCompiler/build/fuji.jar -d "$TMPCLASSOUT" PKJabComp.features \
	&& /bin/cp -rf Resources/* "$TMPCLASSOUT"/
