#!/bin/sh
. ../scripts/global_vars

cd Prevayler
/bin/rm -rf "$TMPCLASSOUT"
mkdir "$TMPCLASSOUT"
javac -cp ../lib/cide.jar:../lib/skaringa.jar:../lib/log4j.jar:../lib/xstream.jar:../lib/javamatch.jar \
        -d "$TMPCLASSOUT" \
        `find sources -name '*.java'`
