#!/bin/sh

cd TankWar
java -Xmx3600m -jar ../../FujiCompiler/build/fuji.jar -fopStatistic TankWarComp.features
#java -Xmx63000m -jar ../../FujiCompiler/build/fuji.jar -fopStatistic TankWarComp.features
