#!/bin/sh

CL=classes
SRC=sources

cd Violet
rm -rf "$CL" "$SRC"
java -Xmx1024m -jar ../../FujiCompiler/build/fuji.jar \
        -d "$CL" -src "$SRC" VioletComp.features \
        && /bin/cp -rf violet_resources/* "$CL" \
        && /bin/cp -rf violet_resources/* "$SRC"
