#!/bin/sh
. ../scripts/global_vars
cd Violet
rm -rf "$TMPCLASSOUT"
java -Xmx128m -jar ../../FujiCompiler/build/fuji.jar \
    -d "$TMPCLASSOUT" VioletComp.features \
    && /bin/cp -rf violet_resources/* "$TMPCLASSOUT"
