#!/bin/sh
. ../scripts/global_vars

cd Violet
rm -rf "$TMPCLASSOUT" "$TMPSRCOUT"
java -Xmx1024m -jar ../../FujiCompiler/build/fuji.jar \
        -d "$TMPCLASSOUT" -src "$TMPSRCOUT" VioletComp.features \
        && /bin/cp -rf violet_resources/* "$TMPCLASSOUT" \
        && /bin/cp -rf violet_resources/* "$TMPSRCOUT"
